version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecommerce-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    environment:
      - PORT=${AUTH_PORT}
      - MONGO_URL=${MONGO_URL}
    depends_on:
      - mongodb
    networks:
      - ecommerce-network

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "${PRODUCT_PORT}:${PRODUCT_PORT}"
    environment:
      - PORT=${PRODUCT_PORT}
      - MONGO_URL=${MONGO_URL}
    depends_on:
      - mongodb
    networks:
      - ecommerce-network

  frontend-service:
    build: ./frontend-service
    container_name: frontend-service
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - PORT=${FRONTEND_PORT}
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  mongodb_data:
