version: '3.8'

services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecommerce-network
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  auth-service:
    image: nairmeghraj/auth-service:latest
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGO_URL=mongodb://mongodb:27017/ecommerce_ci_cd
    networks:
      - ecommerce-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  product-service:
    image: nairmeghraj/product-service:latest
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - MONGO_URL=mongodb://mongodb:27017/ecommerce_ci_cd
    networks:
      - ecommerce-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  frontend-service:
    image: nairmeghraj/frontend-service:latest
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - ecommerce-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

networks:
  ecommerce-network:
    driver: overlay

volumes:
  mongodb_data: